version: "3"
services:
  backend:
    depends_on: 
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: {changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:
